name: Playwright Tests

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.38.0-jammy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            npm-

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.local/share/ms-playwright
          key: playwright-${{ hashFiles('**/playwright.config.js') }}
          restore-keys: |
            playwright-

      - name: Install dependencies
        run: npm ci

      - name: Run Happyflow Tests In Staging Environment
        run: npm run happyflow:stage:chrome

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

          